// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/Sf-go/pkg/models/shared"
	"net/http"
)

type CatControllerUpdateRequest struct {
	UpdateCatDto shared.UpdateCatDto `request:"mediaType=application/json"`
	ID           string              `pathParam:"style=simple,explode=false,name=id"`
}

type CatControllerUpdateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
