// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateCatDto struct {
	Age   float64 `json:"age"`
	Breed string  `json:"breed"`
	Name  string  `json:"name"`
}
